### ISSUE TITLE
Cannot upload XLSX file

### ISSUE THREAD

**Issue by kasnerz** [mschroeder-github/spread2rml#1]
Uploading a XLSX file to the demo running at http://spread2rml.dfki.markus-projects.net/ results in the following error:

```java
java.lang.RuntimeException: java.io.FileNotFoundException: Source 'input/webnlg_dev_table0.xlsx' does not exist
	at de.dfki.sds.spread2rml.demo.Spread2RMLServer.runSpread2RML(Spread2RMLServer.java:213)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1584)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:501)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.FileNotFoundException: Source 'input/webnlg_dev_table0.xlsx' does not exist
	at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1383)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1060)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1028)
	at de.dfki.sds.spread2rml.demo.Spread2RMLServer.runSpread2RML(Spread2RMLServer.java:211)
	... 23 more
```

Sample file:
[webnlg_dev_table0.xlsx](https://github.com/mschroeder-github/spread2rml/files/10258179/webnlg_dev_table0.xlsx)

Screenshot:
![screen-2022-12-19-10-54-31](https://user-images.githubusercontent.com/8361334/208398248-f8dbab01-44fb-4f99-96ec-949447348806.png)

**Comment by mschroeder-github** [comment]
Thank you for your issue. I fixed it and updated it on the server.
![image](https://user-images.githubusercontent.com/19302522/210360790-b8868757-5b61-4006-b02c-32e7cb058e91.png)
